export const USER_LOGIN_REQUEST='USER_SIGNIN_REQUEST';
export const USER_LOGIN_SUCCESS='USER_SIGNIN_SUCCESS';
export const USER_LOGIN_FAIL='USER_SIGNIN_FAIL';

export const USER_LOGOUT='USER_LOGOUT';
//export const USER_LOGOUT_REQUEST='USER_LOGOUT_REQUEST';
//export const USER_LOGOUT_SUCCESS='USER_LOGOUT_SUCCESS';
//export const USER_LOGOUT_FAIL='USER_LOGOUT_FAIL';

export const WEBINAR_LIST_REQUEST='WEBINAR_LIST_REQUEST';
export const WEBINAR_LIST_SUCCESS='WEBINAR_LIST_SUCCESS';
export const WEBINAR_LIST_FAIL='WEBINAR_LIST_FAIL';

export const WEBINART_LIST_REQUEST='WEBINART_LIST_REQUEST';
export const WEBINART_LIST_SUCCESS='WEBINART_LIST_SUCCESS';
export const WEBINART_LIST_FAIL='WEBINART_LIST_FAIL';

export const TOPIC_ADD_REQUEST='TOPIC_ADD_REQUEST';
export const TOPIC_ADD_SUCCESS='TOPIC_ADD_SUCCESS';
export const TOPIC_ADD_FAIL='TOPIC_ADD_FAIL';

export const REGISTED_LIST_REQUEST='REGISTED_LIST_REQUEST';
export const REGISTED_LIST_SUCCESS='REGISTED_LIST_SUCCESS';
export const REGISTED_LIST_FAIL='REGISTED_LIST_FAIL';

export const REGISTER_REQUEST='REGISTER_REQUEST';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';

export const UNREGISTER_REQUEST='UNREGISTER_REQUEST';
export const UNREGISTER_SUCCESS='UNREGISTER_SUCCESS';
export const UNREGISTER_FAIL='UNREGISTER_FAIL';