export const USER_LOGIN_REQUEST='USER_SIGNIN_REQUEST';
export const USER_LOGIN_SUCCESS='USER_SIGNIN_SUCCESS';
export const USER_LOGIN_FAIL='USER_SIGNIN_FAIL';

export const USER_LOGOUT='USER_LOGOUT';
//export const USER_LOGOUT_REQUEST='USER_LOGOUT_REQUEST';
//export const USER_LOGOUT_SUCCESS='USER_LOGOUT_SUCCESS';
//export const USER_LOGOUT_FAIL='USER_LOGOUT_FAIL';

export const WEBINAR_LIST_REQUEST='WEBINAR_LIST_REQUEST';
export const WEBINAR_LIST_SUCCESS='WEBINAR_LIST_SUCCESS';
export const WEBINAR_LIST_FAIL='WEBINAR_LIST_FAIL';

export const TOPIC_ADD_REQUEST='TOPIC_ADD_REQUEST';
export const TOPIC_ADD_SUCCESS='TOPIC_ADD_SUCCESS';
export const TOPIC_ADD_FAIL='TOPIC_ADD_FAIL';